#include "hwacc/peripheral.h"
#include "hwacc/resource.h"

#include "platform/stm32/hwacc/uart.h"

#include "stm32.h"

#include <stddef.h>

PERIPHERAL_INSTANCE_DECL(uart, uart1, USART1,
    PERIPHERAL_INSTANCE_RESOURCE(0, pin_a09, 7),
    PERIPHERAL_INSTANCE_RESOURCE(0, pin_b06, 7),

    PERIPHERAL_INSTANCE_RESOURCE(1, pin_a10, 7),
    PERIPHERAL_INSTANCE_RESOURCE(1, pin_b06, 7),

    PERIPHERAL_INSTANCE_RESOURCE(2, dma_2_2, 4),
    PERIPHERAL_INSTANCE_RESOURCE(2, dma_2_5, 4),
    PERIPHERAL_INSTANCE_RESOURCE(3, dma_2_7, 4)
);

PERIPHERAL_INSTANCE_DECL(uart, uart2, USART2,
    PERIPHERAL_INSTANCE_RESOURCE(0, pin_a02, 7),
    PERIPHERAL_INSTANCE_RESOURCE(0, pin_d05, 7),

    PERIPHERAL_INSTANCE_RESOURCE(1, pin_a03, 7),
    PERIPHERAL_INSTANCE_RESOURCE(1, pin_d06, 7),

    PERIPHERAL_INSTANCE_RESOURCE(2, dma_1_5, 4),
    PERIPHERAL_INSTANCE_RESOURCE(3, dma_1_6, 4)
);

PERIPHERAL_INSTANCE_DECL(uart, uart3, USART3,
    PERIPHERAL_INSTANCE_RESOURCE(0, pin_b10, 7),
    PERIPHERAL_INSTANCE_RESOURCE(0, pin_c10, 7),
    PERIPHERAL_INSTANCE_RESOURCE(0, pin_d08, 7),

    PERIPHERAL_INSTANCE_RESOURCE(1, pin_b11, 7),
    PERIPHERAL_INSTANCE_RESOURCE(1, pin_c11, 7),
    PERIPHERAL_INSTANCE_RESOURCE(1, pin_d09, 7),

    PERIPHERAL_INSTANCE_RESOURCE(2, dma_1_1, 4),
    PERIPHERAL_INSTANCE_RESOURCE(3, dma_1_3, 4),
    PERIPHERAL_INSTANCE_RESOURCE(3, dma_1_4, 7)
);

PERIPHERAL_INSTANCE_DECL(uart, uart4, UART4,
    PERIPHERAL_INSTANCE_RESOURCE(0, pin_a00, 8),
    PERIPHERAL_INSTANCE_RESOURCE(0, pin_c10, 8),
    PERIPHERAL_INSTANCE_RESOURCE(0, pin_h13, 8),

    PERIPHERAL_INSTANCE_RESOURCE(1, pin_a01, 8),
    PERIPHERAL_INSTANCE_RESOURCE(1, pin_c11, 8),
    PERIPHERAL_INSTANCE_RESOURCE(1, pin_h14, 8),
    PERIPHERAL_INSTANCE_RESOURCE(1, pin_i09, 8),

    PERIPHERAL_INSTANCE_RESOURCE(2, dma_1_2, 4),
    PERIPHERAL_INSTANCE_RESOURCE(3, dma_1_4, 4)
);

PERIPHERAL_INSTANCE_DECL(uart, uart5, UART5,
    PERIPHERAL_INSTANCE_RESOURCE(0, pin_c12, 8),

    PERIPHERAL_INSTANCE_RESOURCE(1, pin_d02, 8),

    PERIPHERAL_INSTANCE_RESOURCE(2, dma_1_0, 4),
    PERIPHERAL_INSTANCE_RESOURCE(3, dma_1_7, 4)
);

PERIPHERAL_INSTANCE_DECL(uart, uart6, USART6,
    PERIPHERAL_INSTANCE_RESOURCE(0, pin_c06, 8),
    PERIPHERAL_INSTANCE_RESOURCE(0, pin_g14, 8),

    PERIPHERAL_INSTANCE_RESOURCE(1, pin_c07, 8),
    PERIPHERAL_INSTANCE_RESOURCE(1, pin_g09, 8),

    PERIPHERAL_INSTANCE_RESOURCE(2, dma_2_1, 5),
    PERIPHERAL_INSTANCE_RESOURCE(2, dma_2_2, 5),
    PERIPHERAL_INSTANCE_RESOURCE(3, dma_2_6, 5),
    PERIPHERAL_INSTANCE_RESOURCE(3, dma_2_7, 5)
);

PERIPHERAL_INSTANCE_DECL(uart, uart7, UART7,
    PERIPHERAL_INSTANCE_RESOURCE(0, pin_e08, 8),
    PERIPHERAL_INSTANCE_RESOURCE(0, pin_f07, 8),

    PERIPHERAL_INSTANCE_RESOURCE(1, pin_e07, 8),
    PERIPHERAL_INSTANCE_RESOURCE(1, pin_f06, 8),

    PERIPHERAL_INSTANCE_RESOURCE(2, dma_1_3, 5),
    PERIPHERAL_INSTANCE_RESOURCE(3, dma_1_1, 5)
);

PERIPHERAL_INSTANCE_DECL(uart, uart8, UART8,
    PERIPHERAL_INSTANCE_RESOURCE(0, pin_e01, 8),

    PERIPHERAL_INSTANCE_RESOURCE(1, pin_e00, 8),

    PERIPHERAL_INSTANCE_RESOURCE(2, dma_1_6, 5),
    PERIPHERAL_INSTANCE_RESOURCE(3, dma_1_0, 5)
);
