/*
 * NodeFlight - platform for embedded control systems
 * Copyright (C) 2023  Max Sikström
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#include "core/resource.h"

#include "platform/stm32/resource/gpio.h"
#include "platform/stm32/resource/dma.h"

#include "stm32.h"

/* Not used, but keep for reference */
#define RS_TYPE_NONE 0
#define RS_TYPE_GPIO 1
#define RS_TYPE_DMA  2

RS_DECL(pin_none, RS_TYPE_GPIO, RS_COUNT_INF, GPIO_ID_NONE);

#ifdef GPIOA
RS_DECL(pin_a00, RS_TYPE_GPIO, 1, GPIO_ID(a00));
RS_DECL(pin_a01, RS_TYPE_GPIO, 1, GPIO_ID(a01));
RS_DECL(pin_a02, RS_TYPE_GPIO, 1, GPIO_ID(a02));
RS_DECL(pin_a03, RS_TYPE_GPIO, 1, GPIO_ID(a03));
RS_DECL(pin_a04, RS_TYPE_GPIO, 1, GPIO_ID(a04));
RS_DECL(pin_a05, RS_TYPE_GPIO, 1, GPIO_ID(a05));
RS_DECL(pin_a06, RS_TYPE_GPIO, 1, GPIO_ID(a06));
RS_DECL(pin_a07, RS_TYPE_GPIO, 1, GPIO_ID(a07));
RS_DECL(pin_a08, RS_TYPE_GPIO, 1, GPIO_ID(a08));
RS_DECL(pin_a09, RS_TYPE_GPIO, 1, GPIO_ID(a09));
RS_DECL(pin_a10, RS_TYPE_GPIO, 1, GPIO_ID(a10));
RS_DECL(pin_a11, RS_TYPE_GPIO, 1, GPIO_ID(a11));
RS_DECL(pin_a12, RS_TYPE_GPIO, 1, GPIO_ID(a12));
RS_DECL(pin_a13, RS_TYPE_GPIO, 1, GPIO_ID(a13));
RS_DECL(pin_a14, RS_TYPE_GPIO, 1, GPIO_ID(a14));
RS_DECL(pin_a15, RS_TYPE_GPIO, 1, GPIO_ID(a15));
#endif

#ifdef GPIOB
RS_DECL(pin_b00, RS_TYPE_GPIO, 1, GPIO_ID(b00));
RS_DECL(pin_b01, RS_TYPE_GPIO, 1, GPIO_ID(b01));
RS_DECL(pin_b02, RS_TYPE_GPIO, 1, GPIO_ID(b02));
RS_DECL(pin_b03, RS_TYPE_GPIO, 1, GPIO_ID(b03));
RS_DECL(pin_b04, RS_TYPE_GPIO, 1, GPIO_ID(b04));
RS_DECL(pin_b05, RS_TYPE_GPIO, 1, GPIO_ID(b05));
RS_DECL(pin_b06, RS_TYPE_GPIO, 1, GPIO_ID(b06));
RS_DECL(pin_b07, RS_TYPE_GPIO, 1, GPIO_ID(b07));
RS_DECL(pin_b08, RS_TYPE_GPIO, 1, GPIO_ID(b08));
RS_DECL(pin_b09, RS_TYPE_GPIO, 1, GPIO_ID(b09));
RS_DECL(pin_b10, RS_TYPE_GPIO, 1, GPIO_ID(b10));
RS_DECL(pin_b11, RS_TYPE_GPIO, 1, GPIO_ID(b11));
RS_DECL(pin_b12, RS_TYPE_GPIO, 1, GPIO_ID(b12));
RS_DECL(pin_b13, RS_TYPE_GPIO, 1, GPIO_ID(b13));
RS_DECL(pin_b14, RS_TYPE_GPIO, 1, GPIO_ID(b14));
RS_DECL(pin_b15, RS_TYPE_GPIO, 1, GPIO_ID(b15));
#endif

#ifdef GPIOC
RS_DECL(pin_c00, RS_TYPE_GPIO, 1, GPIO_ID(c00));
RS_DECL(pin_c01, RS_TYPE_GPIO, 1, GPIO_ID(c01));
RS_DECL(pin_c02, RS_TYPE_GPIO, 1, GPIO_ID(c02));
RS_DECL(pin_c03, RS_TYPE_GPIO, 1, GPIO_ID(c03));
RS_DECL(pin_c04, RS_TYPE_GPIO, 1, GPIO_ID(c04));
RS_DECL(pin_c05, RS_TYPE_GPIO, 1, GPIO_ID(c05));
RS_DECL(pin_c06, RS_TYPE_GPIO, 1, GPIO_ID(c06));
RS_DECL(pin_c07, RS_TYPE_GPIO, 1, GPIO_ID(c07));
RS_DECL(pin_c08, RS_TYPE_GPIO, 1, GPIO_ID(c08));
RS_DECL(pin_c09, RS_TYPE_GPIO, 1, GPIO_ID(c09));
RS_DECL(pin_c10, RS_TYPE_GPIO, 1, GPIO_ID(c10));
RS_DECL(pin_c11, RS_TYPE_GPIO, 1, GPIO_ID(c11));
RS_DECL(pin_c12, RS_TYPE_GPIO, 1, GPIO_ID(c12));
RS_DECL(pin_c13, RS_TYPE_GPIO, 1, GPIO_ID(c13));
RS_DECL(pin_c14, RS_TYPE_GPIO, 1, GPIO_ID(c14));
RS_DECL(pin_c15, RS_TYPE_GPIO, 1, GPIO_ID(c15));
#endif

#ifdef GPIOD
RS_DECL(pin_d00, RS_TYPE_GPIO, 1, GPIO_ID(d00));
RS_DECL(pin_d01, RS_TYPE_GPIO, 1, GPIO_ID(d01));
RS_DECL(pin_d02, RS_TYPE_GPIO, 1, GPIO_ID(d02));
RS_DECL(pin_d03, RS_TYPE_GPIO, 1, GPIO_ID(d03));
RS_DECL(pin_d04, RS_TYPE_GPIO, 1, GPIO_ID(d04));
RS_DECL(pin_d05, RS_TYPE_GPIO, 1, GPIO_ID(d05));
RS_DECL(pin_d06, RS_TYPE_GPIO, 1, GPIO_ID(d06));
RS_DECL(pin_d07, RS_TYPE_GPIO, 1, GPIO_ID(d07));
RS_DECL(pin_d08, RS_TYPE_GPIO, 1, GPIO_ID(d08));
RS_DECL(pin_d09, RS_TYPE_GPIO, 1, GPIO_ID(d09));
RS_DECL(pin_d10, RS_TYPE_GPIO, 1, GPIO_ID(d10));
RS_DECL(pin_d11, RS_TYPE_GPIO, 1, GPIO_ID(d11));
RS_DECL(pin_d12, RS_TYPE_GPIO, 1, GPIO_ID(d12));
RS_DECL(pin_d13, RS_TYPE_GPIO, 1, GPIO_ID(d13));
RS_DECL(pin_d14, RS_TYPE_GPIO, 1, GPIO_ID(d14));
RS_DECL(pin_d15, RS_TYPE_GPIO, 1, GPIO_ID(d15));
#endif

#ifdef GPIOE
RS_DECL(pin_e00, RS_TYPE_GPIO, 1, GPIO_ID(e00));
RS_DECL(pin_e01, RS_TYPE_GPIO, 1, GPIO_ID(e01));
RS_DECL(pin_e02, RS_TYPE_GPIO, 1, GPIO_ID(e02));
RS_DECL(pin_e03, RS_TYPE_GPIO, 1, GPIO_ID(e03));
RS_DECL(pin_e04, RS_TYPE_GPIO, 1, GPIO_ID(e04));
RS_DECL(pin_e05, RS_TYPE_GPIO, 1, GPIO_ID(e05));
RS_DECL(pin_e06, RS_TYPE_GPIO, 1, GPIO_ID(e06));
RS_DECL(pin_e07, RS_TYPE_GPIO, 1, GPIO_ID(e07));
RS_DECL(pin_e08, RS_TYPE_GPIO, 1, GPIO_ID(e08));
RS_DECL(pin_e09, RS_TYPE_GPIO, 1, GPIO_ID(e09));
RS_DECL(pin_e10, RS_TYPE_GPIO, 1, GPIO_ID(e10));
RS_DECL(pin_e11, RS_TYPE_GPIO, 1, GPIO_ID(e11));
RS_DECL(pin_e12, RS_TYPE_GPIO, 1, GPIO_ID(e12));
RS_DECL(pin_e13, RS_TYPE_GPIO, 1, GPIO_ID(e13));
RS_DECL(pin_e14, RS_TYPE_GPIO, 1, GPIO_ID(e14));
RS_DECL(pin_e15, RS_TYPE_GPIO, 1, GPIO_ID(e15));
#endif

#ifdef GPIOF
RS_DECL(pin_f00, RS_TYPE_GPIO, 1, GPIO_ID(f00));
RS_DECL(pin_f01, RS_TYPE_GPIO, 1, GPIO_ID(f01));
RS_DECL(pin_f02, RS_TYPE_GPIO, 1, GPIO_ID(f02));
RS_DECL(pin_f03, RS_TYPE_GPIO, 1, GPIO_ID(f03));
RS_DECL(pin_f04, RS_TYPE_GPIO, 1, GPIO_ID(f04));
RS_DECL(pin_f05, RS_TYPE_GPIO, 1, GPIO_ID(f05));
RS_DECL(pin_f06, RS_TYPE_GPIO, 1, GPIO_ID(f06));
RS_DECL(pin_f07, RS_TYPE_GPIO, 1, GPIO_ID(f07));
RS_DECL(pin_f08, RS_TYPE_GPIO, 1, GPIO_ID(f08));
RS_DECL(pin_f09, RS_TYPE_GPIO, 1, GPIO_ID(f09));
RS_DECL(pin_f10, RS_TYPE_GPIO, 1, GPIO_ID(f10));
RS_DECL(pin_f11, RS_TYPE_GPIO, 1, GPIO_ID(f11));
RS_DECL(pin_f12, RS_TYPE_GPIO, 1, GPIO_ID(f12));
RS_DECL(pin_f13, RS_TYPE_GPIO, 1, GPIO_ID(f13));
RS_DECL(pin_f14, RS_TYPE_GPIO, 1, GPIO_ID(f14));
RS_DECL(pin_f15, RS_TYPE_GPIO, 1, GPIO_ID(f15));
#endif

#ifdef GPIOG
RS_DECL(pin_g00, RS_TYPE_GPIO, 1, GPIO_ID(g00));
RS_DECL(pin_g01, RS_TYPE_GPIO, 1, GPIO_ID(g01));
RS_DECL(pin_g02, RS_TYPE_GPIO, 1, GPIO_ID(g02));
RS_DECL(pin_g03, RS_TYPE_GPIO, 1, GPIO_ID(g03));
RS_DECL(pin_g04, RS_TYPE_GPIO, 1, GPIO_ID(g04));
RS_DECL(pin_g05, RS_TYPE_GPIO, 1, GPIO_ID(g05));
RS_DECL(pin_g06, RS_TYPE_GPIO, 1, GPIO_ID(g06));
RS_DECL(pin_g07, RS_TYPE_GPIO, 1, GPIO_ID(g07));
RS_DECL(pin_g08, RS_TYPE_GPIO, 1, GPIO_ID(g08));
RS_DECL(pin_g09, RS_TYPE_GPIO, 1, GPIO_ID(g09));
RS_DECL(pin_g10, RS_TYPE_GPIO, 1, GPIO_ID(g10));
RS_DECL(pin_g11, RS_TYPE_GPIO, 1, GPIO_ID(g11));
RS_DECL(pin_g12, RS_TYPE_GPIO, 1, GPIO_ID(g12));
RS_DECL(pin_g13, RS_TYPE_GPIO, 1, GPIO_ID(g13));
RS_DECL(pin_g14, RS_TYPE_GPIO, 1, GPIO_ID(g14));
RS_DECL(pin_g15, RS_TYPE_GPIO, 1, GPIO_ID(g15));
#endif

#ifdef GPIOH
RS_DECL(pin_h00, RS_TYPE_GPIO, 1, GPIO_ID(h00));
RS_DECL(pin_h01, RS_TYPE_GPIO, 1, GPIO_ID(h01));
RS_DECL(pin_h02, RS_TYPE_GPIO, 1, GPIO_ID(h02));
RS_DECL(pin_h03, RS_TYPE_GPIO, 1, GPIO_ID(h03));
RS_DECL(pin_h04, RS_TYPE_GPIO, 1, GPIO_ID(h04));
RS_DECL(pin_h05, RS_TYPE_GPIO, 1, GPIO_ID(h05));
RS_DECL(pin_h06, RS_TYPE_GPIO, 1, GPIO_ID(h06));
RS_DECL(pin_h07, RS_TYPE_GPIO, 1, GPIO_ID(h07));
RS_DECL(pin_h08, RS_TYPE_GPIO, 1, GPIO_ID(h08));
RS_DECL(pin_h09, RS_TYPE_GPIO, 1, GPIO_ID(h09));
RS_DECL(pin_h10, RS_TYPE_GPIO, 1, GPIO_ID(h10));
RS_DECL(pin_h11, RS_TYPE_GPIO, 1, GPIO_ID(h11));
RS_DECL(pin_h12, RS_TYPE_GPIO, 1, GPIO_ID(h12));
RS_DECL(pin_h13, RS_TYPE_GPIO, 1, GPIO_ID(h13));
RS_DECL(pin_h14, RS_TYPE_GPIO, 1, GPIO_ID(h14));
RS_DECL(pin_h15, RS_TYPE_GPIO, 1, GPIO_ID(h15));
#endif

#ifdef GPIOI
RS_DECL(pin_i00, RS_TYPE_GPIO, 1, GPIO_ID(i00));
RS_DECL(pin_i01, RS_TYPE_GPIO, 1, GPIO_ID(i01));
RS_DECL(pin_i02, RS_TYPE_GPIO, 1, GPIO_ID(i02));
RS_DECL(pin_i03, RS_TYPE_GPIO, 1, GPIO_ID(i03));
RS_DECL(pin_i04, RS_TYPE_GPIO, 1, GPIO_ID(i04));
RS_DECL(pin_i05, RS_TYPE_GPIO, 1, GPIO_ID(i05));
RS_DECL(pin_i06, RS_TYPE_GPIO, 1, GPIO_ID(i06));
RS_DECL(pin_i07, RS_TYPE_GPIO, 1, GPIO_ID(i07));
RS_DECL(pin_i08, RS_TYPE_GPIO, 1, GPIO_ID(i08));
RS_DECL(pin_i09, RS_TYPE_GPIO, 1, GPIO_ID(i09));
RS_DECL(pin_i10, RS_TYPE_GPIO, 1, GPIO_ID(i10));
RS_DECL(pin_i11, RS_TYPE_GPIO, 1, GPIO_ID(i11));
RS_DECL(pin_i12, RS_TYPE_GPIO, 1, GPIO_ID(i12));
RS_DECL(pin_i13, RS_TYPE_GPIO, 1, GPIO_ID(i13));
RS_DECL(pin_i14, RS_TYPE_GPIO, 1, GPIO_ID(i14));
RS_DECL(pin_i15, RS_TYPE_GPIO, 1, GPIO_ID(i15));
#endif

#ifdef GPIOJ
RS_DECL(pin_j00, RS_TYPE_GPIO, 1, GPIO_ID(j00));
RS_DECL(pin_j01, RS_TYPE_GPIO, 1, GPIO_ID(j01));
RS_DECL(pin_j02, RS_TYPE_GPIO, 1, GPIO_ID(j02));
RS_DECL(pin_j03, RS_TYPE_GPIO, 1, GPIO_ID(j03));
RS_DECL(pin_j04, RS_TYPE_GPIO, 1, GPIO_ID(j04));
RS_DECL(pin_j05, RS_TYPE_GPIO, 1, GPIO_ID(j05));
RS_DECL(pin_j06, RS_TYPE_GPIO, 1, GPIO_ID(j06));
RS_DECL(pin_j07, RS_TYPE_GPIO, 1, GPIO_ID(j07));
RS_DECL(pin_j08, RS_TYPE_GPIO, 1, GPIO_ID(j08));
RS_DECL(pin_j09, RS_TYPE_GPIO, 1, GPIO_ID(j09));
RS_DECL(pin_j10, RS_TYPE_GPIO, 1, GPIO_ID(j10));
RS_DECL(pin_j11, RS_TYPE_GPIO, 1, GPIO_ID(j11));
RS_DECL(pin_j12, RS_TYPE_GPIO, 1, GPIO_ID(j12));
RS_DECL(pin_j13, RS_TYPE_GPIO, 1, GPIO_ID(j13));
RS_DECL(pin_j14, RS_TYPE_GPIO, 1, GPIO_ID(j14));
RS_DECL(pin_j15, RS_TYPE_GPIO, 1, GPIO_ID(j15));
#endif

#ifdef GPIOK
RS_DECL(pin_k00, RS_TYPE_GPIO, 1, GPIO_ID(k00));
RS_DECL(pin_k01, RS_TYPE_GPIO, 1, GPIO_ID(k01));
RS_DECL(pin_k02, RS_TYPE_GPIO, 1, GPIO_ID(k02));
RS_DECL(pin_k03, RS_TYPE_GPIO, 1, GPIO_ID(k03));
RS_DECL(pin_k04, RS_TYPE_GPIO, 1, GPIO_ID(k04));
RS_DECL(pin_k05, RS_TYPE_GPIO, 1, GPIO_ID(k05));
RS_DECL(pin_k06, RS_TYPE_GPIO, 1, GPIO_ID(k06));
RS_DECL(pin_k07, RS_TYPE_GPIO, 1, GPIO_ID(k07));
RS_DECL(pin_k08, RS_TYPE_GPIO, 1, GPIO_ID(k08));
RS_DECL(pin_k09, RS_TYPE_GPIO, 1, GPIO_ID(k09));
RS_DECL(pin_k10, RS_TYPE_GPIO, 1, GPIO_ID(k10));
RS_DECL(pin_k11, RS_TYPE_GPIO, 1, GPIO_ID(k11));
RS_DECL(pin_k12, RS_TYPE_GPIO, 1, GPIO_ID(k12));
RS_DECL(pin_k13, RS_TYPE_GPIO, 1, GPIO_ID(k13));
RS_DECL(pin_k14, RS_TYPE_GPIO, 1, GPIO_ID(k14));
RS_DECL(pin_k15, RS_TYPE_GPIO, 1, GPIO_ID(k15));
#endif

RS_DECL(dma_none, RS_TYPE_DMA, RS_COUNT_INF, DMA_ID_NONE);

RS_DECL(dma_1_0, RS_TYPE_DMA, 1, DMA_ID(1, 0));
RS_DECL(dma_1_1, RS_TYPE_DMA, 1, DMA_ID(1, 1));
RS_DECL(dma_1_2, RS_TYPE_DMA, 1, DMA_ID(1, 2));
RS_DECL(dma_1_3, RS_TYPE_DMA, 1, DMA_ID(1, 3));
RS_DECL(dma_1_4, RS_TYPE_DMA, 1, DMA_ID(1, 4));
RS_DECL(dma_1_5, RS_TYPE_DMA, 1, DMA_ID(1, 5));
RS_DECL(dma_1_6, RS_TYPE_DMA, 1, DMA_ID(1, 6));
RS_DECL(dma_1_7, RS_TYPE_DMA, 1, DMA_ID(1, 7));

RS_DECL(dma_2_0, RS_TYPE_DMA, 1, DMA_ID(2, 0));
RS_DECL(dma_2_1, RS_TYPE_DMA, 1, DMA_ID(2, 1));
RS_DECL(dma_2_2, RS_TYPE_DMA, 1, DMA_ID(2, 2));
RS_DECL(dma_2_3, RS_TYPE_DMA, 1, DMA_ID(2, 3));
RS_DECL(dma_2_4, RS_TYPE_DMA, 1, DMA_ID(2, 4));
RS_DECL(dma_2_5, RS_TYPE_DMA, 1, DMA_ID(2, 5));
RS_DECL(dma_2_6, RS_TYPE_DMA, 1, DMA_ID(2, 6));
RS_DECL(dma_2_7, RS_TYPE_DMA, 1, DMA_ID(2, 7));
